name: Setup
description: Setup the environment for the project
runs:
  using: "composite"
  steps:
  - name: Read nvmrc file
    id: nvm
    shell: bash
    run: echo "NVMRC=$(cat .nvmrc)" >> "$GITHUB_OUTPUT"
  - name: Setup pnpm
    uses: pnpm/action-setup@v4
  - name: Setup node
    uses: actions/setup-node@v4
    with:
      node-version: ${{ steps.nvm.outputs.NVMRC }}
      cache: 'pnpm'
  - name: Install dependencies
    run: pnpm install --frozen-lockfile
    shell: bash
