name: Setup
description: Setup the environment for the project
runs:
  using: "composite"
  steps:
  - name: Read nvmrc file
    run: echo "{name}={$(cat .nvmrc)}" >> $GITHUB_OUTPUT
    shell: bash
    id: nvm
  - name: Setup node
    uses: actions/setup-node@v1
    with:
      node-version: '${{ steps.nvm.outputs.NVMRC }}'
  - name: Setup pnpm
    uses: pnpm/action-setup@v4
  - name: Install dependencies
    run: pnpm i
    shell: bash
