[supervisord]
nodaemon=true
user=dev
logfile=/home/dev/supervisord.log
pidfile=/home/dev/supervisord.pid

[program:sshd]
command=/usr/sbin/sshd -D -e -h /home/dev/.ssh/id_sshd
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:code-server]
command=code-server --bind-addr 0.0.0.0:8080 --auth none /home/dev/workspace
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:deepseekharness]
command= dsh web  --trusted-host dev.gutschi.site:8444 --no-open --host 0.0.0.0 --port 3080
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

