import { AccountController } from './rest/AccountController';
import { Engine } from './rest/Engine';
import { InMemoryAccountRepository } from './persistence/inmemory/InMemoryAccountRepository';
import pino from 'pino';
import { Accounts } from './domain/usecases/Accounts';
import { Bookings } from './domain/usecases/Bookings';
import { BookingController } from './rest/BookingController';
import { InMemoryBookingRepository } from './persistence/inmemory/InMemoryBookingRepository';
import { InMemoryDB } from './persistence/inmemory/InMemoryDB';

const logger = pino({ level: 'debug' });
const imMemoryDB = new InMemoryDB();
const accountRepository = new InMemoryAccountRepository(imMemoryDB);
const manageAccounts = new Accounts(logger, accountRepository);
const accountController = new AccountController(logger, manageAccounts);
const bookingRepository = new InMemoryBookingRepository(imMemoryDB);
const manageBookings = new Bookings(logger, manageAccounts, bookingRepository);
const bookingController = new BookingController(logger, manageBookings);
const engine = new Engine(8080, logger, [ accountController, bookingController ]);
engine.run();
