#!/usr/bin/env node
// Orchestrates the docker-compose smoke suite.
//
//   certs -> verify /etc/hosts -> compose up (wait for health) ->
//   explicit readiness polling -> vitest -> ALWAYS compose down
//
// Run from anywhere:  pnpm --filter @homeserver/integration-test test
// (or:  node integration-test/scripts/run-smoke.mjs)
//
// Environment:
//   AI_API_KEY        only real secret; read from ../.env if not already set
//   SMOKE_KEEP_STACK=1   keep the stack running after the run (debugging)
//   SMOKE_TIMEOUT_MS     overall readiness timeout (default 5 min)

import { spawnSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import dotenv from 'dotenv'

const here = dirname(fileURLToPath(import.meta.url))
const PKG_ROOT = resolve(here, '..')
const REPO_ROOT = resolve(PKG_ROOT, '..')

// The whole stack runs on self-signed certificates (generated by
// generate-certs.sh); relax TLS verification for this test-only process.
process.env.NODE_TLS_REJECT_UNAUTHORIZED ??= '0'

const COMPOSE_BASE = join(REPO_ROOT, 'infrastructure', 'docker-compose.yml')
const COMPOSE_OVERRIDE = join(PKG_ROOT, 'docker-compose.ci.yml')
const ENV_TEST = join(PKG_ROOT, 'env.test')
const INFRA_ENV = join(REPO_ROOT, 'infrastructure', '.env')
const ROOT_ENV = join(REPO_ROOT, '.env')

const HOSTS = [
  ['127.0.0.1', 'dev.gutschi.site'],
  ['127.0.0.1', 'www.gutschi.site'],
  ['127.0.0.1', 'logs.gutschi.site'],
  ['127.0.0.1', 'mock-oidc-server'],
]
const HOSTS_FILE = '/etc/hosts'

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

function log(step, message) {
  console.log(`[smoke] ${step}: ${message}`)
}

function run(cmd, args, opts = {}) {
  const result = spawnSync(cmd, args, { stdio: 'inherit', env: process.env, ...opts })
  return { status: result.status ?? 1, signal: result.signal }
}

function runCapture(cmd, args, opts = {}) {
  const result = spawnSync(cmd, args, { encoding: 'utf8', env: process.env, ...opts })
  return { status: result.status ?? 1, stdout: (result.stdout ?? '').trim(), stderr: (result.stderr ?? '').trim() }
}

function parseEnvFile(path) {
  if (!existsSync(path)) return {}
  return dotenv.parse(readFileSync(path, 'utf8'))
}

// ---------------------------------------------------------------------------
// 1. docker availability
// ---------------------------------------------------------------------------

function requireDocker() {
  const check = runCapture('docker', ['version', '--format', '{{.Server.Version}}'])
  if (check.status !== 0) {
    console.error('[smoke] ERROR: docker is not available or the daemon is not running.')
    console.error('[smoke] The smoke suite boots the full docker-compose stack; install Docker and retry.')
    process.exit(1)
  }
  log('docker', `daemon available (server ${check.stdout})`)
}

// ---------------------------------------------------------------------------
// 2. certificates
// ---------------------------------------------------------------------------

function generateCerts() {
  const script = join(PKG_ROOT, 'scripts', 'generate-certs.sh')
  const result = run('bash', [script])
  if (result.status !== 0) {
    console.error('[smoke] ERROR: certificate generation failed')
    process.exit(result.status)
  }
  log('certs', 'self-signed certificates generated')
}

// ---------------------------------------------------------------------------
// 3. /etc/hosts (so host-side checks + the browser reach the stack)
// ---------------------------------------------------------------------------

function ensureHosts() {
  let current = ''
  try {
    current = readFileSync(HOSTS_FILE, 'utf8')
  }
  catch (error) {
    console.error(`[smoke] ERROR: cannot read ${HOSTS_FILE}: ${error instanceof Error ? error.message : String(error)}`)
    console.error('[smoke] The smoke suite requires the hosts below to resolve to 127.0.0.1 (e.g. in /etc/hosts).')
    for (const [ip, name] of HOSTS) console.error(`[smoke]   ${ip} ${name}`)
    process.exit(1)
  }
  const missing = HOSTS.filter(([ip, name]) => !new RegExp(`^\\s*${ip}\\s+.*${name}\\b`, 'm').test(current))
  if (missing.length > 0) {
    console.error(`[smoke] ERROR: ${HOSTS_FILE} is missing entries that the smoke suite needs (it never edits the hosts file):`)
    for (const [ip, name] of missing) console.error(`[smoke]   ${ip} ${name}`)
    console.error('[smoke] Add them (e.g. "sudo tee -a /etc/hosts") and re-run.')
    process.exit(1)
  }
  log('hosts', 'required entries are present')
}

// ---------------------------------------------------------------------------
// 4. infrastructure/.env + AI_API_KEY
// ---------------------------------------------------------------------------

function ensureProjectEnv() {
  if (!existsSync(INFRA_ENV)) {
    writeFileSync(INFRA_ENV, readFileSync(ENV_TEST))
    log('env', `created ${join('infrastructure', '.env')} from env.test (git-ignored)`)
  }
  else {
    log('env', 'infrastructure/.env already exists (env.test still wins via env_file override)')
  }
}

function loadAiApiKey() {
  if (process.env.AI_API_KEY) {
    log('env', 'AI_API_KEY provided by environment')
    return
  }
  const rootEnv = parseEnvFile(ROOT_ENV)
  if (rootEnv.AI_API_KEY) {
    process.env.AI_API_KEY = rootEnv.AI_API_KEY
    log('env', 'AI_API_KEY loaded from ../.env')
  }
  else {
    log('env', 'WARNING: AI_API_KEY is not set anywhere; the assistant cannot start and the greeting check will fail')
  }
}

// ---------------------------------------------------------------------------
// 5. compose up / down
// ---------------------------------------------------------------------------

function composeArgs(extra = []) {
  return ['compose', '-f', COMPOSE_BASE, '-f', COMPOSE_OVERRIDE, ...extra]
}

function composeUp() {
  log('compose', 'starting stack (up -d --wait --remove-orphans)')
  const result = run('docker', composeArgs(['up', '-d', '--wait', '--wait-timeout', '300', '--remove-orphans']))
  if (result.status !== 0) {
    throw new Error(`docker compose up failed (exit ${String(result.status)})`)
  }
  log('compose', 'stack is up; healthchecked services are healthy')
}

function composeDown() {
  if (process.env.SMOKE_KEEP_STACK === '1') {
    log('compose', 'SMOKE_KEEP_STACK=1 - leaving the stack running')
    return
  }
  log('compose', 'tearing the stack down (down --remove-orphans -v)')
  const result = run('docker', composeArgs(['down', '--remove-orphans', '-v']))
  if (result.status !== 0) {
    console.error('[smoke] ERROR: docker compose down failed - check for orphan containers manually')
  }
}

// ---------------------------------------------------------------------------
// 6. run the vitest checks
// ---------------------------------------------------------------------------

function runChecks() {
  log('checks', 'running vitest smoke checks')
  const result = spawnSync('pnpm', ['exec', 'vitest', 'run'], {
    cwd: PKG_ROOT,
    stdio: 'inherit',
    env: { ...process.env, NODE_TLS_REJECT_UNAUTHORIZED: '0' },
  })
  return result.status ?? 1
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

async function main() {
  requireDocker()
  generateCerts()
  ensureHosts()
  ensureProjectEnv()
  loadAiApiKey()

  let exitCode = 1
  try {
    composeUp()
    exitCode = runChecks()
  }
  catch (error) {
    console.error(`[smoke] ERROR: ${error instanceof Error ? error.message : String(error)}`)
  }
  finally {
    // Always tear down (also when compose up itself failed), unless the user
    // explicitly asked to keep the stack for debugging.
    composeDown()
  }

  if (exitCode === 0) log('done', 'smoke suite passed')
  else console.error(`[smoke] smoke suite failed (exit ${String(exitCode)})`)
  process.exit(exitCode)
}

void main()
