#!/usr/bin/env node
// Orchestrates the docker-compose smoke suite.
//
//   certs -> verify /etc/hosts -> compose up (wait for health) ->
//   explicit readiness polling -> vitest -> ALWAYS compose down
//
// Run from anywhere:  pnpm --filter @homeserver/integration-test test
// (or:  node integration-test/scripts/run-smoke.mjs)
//
// Environment:
//   AI_API_KEY        only real secret; read from ../.env if not already set
//   SMOKE_KEEP_STACK=1   keep the stack running after the run (debugging)
//   SMOKE_TIMEOUT_MS     overall readiness timeout (default 5 min)

import { spawnSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import dgram from 'node:dgram'
import net from 'node:net'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import dotenv from 'dotenv'

const here = dirname(fileURLToPath(import.meta.url))
const PKG_ROOT = resolve(here, '..')
const REPO_ROOT = resolve(PKG_ROOT, '..')

// The whole stack runs on self-signed certificates (generated by
// generate-certs.sh); relax TLS verification for this test-only process.
process.env.NODE_TLS_REJECT_UNAUTHORIZED ??= '0'

const COMPOSE_BASE = join(REPO_ROOT, 'infrastructure', 'docker-compose.yml')
const COMPOSE_OVERRIDE = join(PKG_ROOT, 'docker-compose.ci.yml')
const ENV_TEST = join(PKG_ROOT, 'env.test')
const INFRA_ENV = join(REPO_ROOT, 'infrastructure', '.env')
const ROOT_ENV = join(REPO_ROOT, '.env')

const HOSTS = [
  ['127.0.0.1', 'dev.gutschi.site'],
  ['127.0.0.1', 'www.gutschi.site'],
  ['127.0.0.1', 'logs.gutschi.site'],
  ['127.0.0.1', 'mock-oidc-server'],
]
const HOSTS_FILE = '/etc/hosts'

const READY_TIMEOUT_MS = Number(process.env.SMOKE_TIMEOUT_MS ?? 300_000)
const POLL_INTERVAL_MS = 2_000

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

function log(step, message) {
  console.log(`[smoke] ${step}: ${message}`)
}

function run(cmd, args, opts = {}) {
  const result = spawnSync(cmd, args, { stdio: 'inherit', env: process.env, ...opts })
  return { status: result.status ?? 1, signal: result.signal }
}

function runCapture(cmd, args, opts = {}) {
  const result = spawnSync(cmd, args, { encoding: 'utf8', env: process.env, ...opts })
  return { status: result.status ?? 1, stdout: (result.stdout ?? '').trim(), stderr: (result.stderr ?? '').trim() }
}

function parseEnvFile(path) {
  if (!existsSync(path)) return {}
  return dotenv.parse(readFileSync(path, 'utf8'))
}

// ---------------------------------------------------------------------------
// 1. docker availability
// ---------------------------------------------------------------------------

function requireDocker() {
  const check = runCapture('docker', ['version', '--format', '{{.Server.Version}}'])
  if (check.status !== 0) {
    console.error('[smoke] ERROR: docker is not available or the daemon is not running.')
    console.error('[smoke] The smoke suite boots the full docker-compose stack; install Docker and retry.')
    process.exit(1)
  }
  log('docker', `daemon available (server ${check.stdout})`)
}

// ---------------------------------------------------------------------------
// 2. certificates
// ---------------------------------------------------------------------------

function generateCerts() {
  const script = join(PKG_ROOT, 'scripts', 'generate-certs.sh')
  const result = run('bash', [script])
  if (result.status !== 0) {
    console.error('[smoke] ERROR: certificate generation failed')
    process.exit(result.status)
  }
  log('certs', 'self-signed certificates generated')
}

// ---------------------------------------------------------------------------
// 3. /etc/hosts (so host-side checks + the browser reach the stack)
// ---------------------------------------------------------------------------

function ensureHosts() {
  let current = ''
  try {
    current = readFileSync(HOSTS_FILE, 'utf8')
  }
  catch (error) {
    console.error(`[smoke] ERROR: cannot read ${HOSTS_FILE}: ${error instanceof Error ? error.message : String(error)}`)
    console.error('[smoke] The smoke suite requires the hosts below to resolve to 127.0.0.1 (e.g. in /etc/hosts).')
    for (const [ip, name] of HOSTS) console.error(`[smoke]   ${ip} ${name}`)
    process.exit(1)
  }
  const missing = HOSTS.filter(([ip, name]) => !new RegExp(`^\\s*${ip}\\s+${name}\\b`, 'm').test(current))
  if (missing.length > 0) {
    console.error(`[smoke] ERROR: ${HOSTS_FILE} is missing entries that the smoke suite needs (it never edits the hosts file):`)
    for (const [ip, name] of missing) console.error(`[smoke]   ${ip} ${name}`)
    console.error('[smoke] Add them (e.g. "sudo tee -a /etc/hosts") and re-run.')
    process.exit(1)
  }
  log('hosts', 'required entries are present')
}

// ---------------------------------------------------------------------------
// 4. infrastructure/.env + AI_API_KEY
// ---------------------------------------------------------------------------

function ensureProjectEnv() {
  if (!existsSync(INFRA_ENV)) {
    writeFileSync(INFRA_ENV, readFileSync(ENV_TEST))
    log('env', `created ${join('infrastructure', '.env')} from env.test (git-ignored)`)
  }
  else {
    log('env', 'infrastructure/.env already exists (env.test still wins via env_file override)')
  }
}

function loadAiApiKey() {
  if (process.env.AI_API_KEY) {
    log('env', 'AI_API_KEY provided by environment')
    return
  }
  const rootEnv = parseEnvFile(ROOT_ENV)
  if (rootEnv.AI_API_KEY) {
    process.env.AI_API_KEY = rootEnv.AI_API_KEY
    log('env', 'AI_API_KEY loaded from ../.env')
  }
  else {
    log('env', 'WARNING: AI_API_KEY is not set anywhere; the assistant cannot start and the greeting check will fail')
  }
}

// ---------------------------------------------------------------------------
// 5. compose up / down
// ---------------------------------------------------------------------------

function composeArgs(extra = []) {
  return ['-f', COMPOSE_BASE, '-f', COMPOSE_OVERRIDE, ...extra]
}

function composeUp() {
  log('compose', 'starting stack (up -d --wait --remove-orphans)')
  const result = run('docker', composeArgs(['up', '-d', '--wait', '--wait-timeout', '300', '--remove-orphans']))
  if (result.status !== 0) {
    throw new Error(`docker compose up failed (exit ${String(result.status)})`)
  }
  log('compose', 'stack is up; healthchecked services are healthy')
}

function composeDown() {
  if (process.env.SMOKE_KEEP_STACK === '1') {
    log('compose', 'SMOKE_KEEP_STACK=1 - leaving the stack running')
    return
  }
  log('compose', 'tearing the stack down (down --remove-orphans -v)')
  const result = run('docker', composeArgs(['down', '--remove-orphans', '-v']))
  if (result.status !== 0) {
    console.error('[smoke] ERROR: docker compose down failed - check for orphan containers manually')
  }
}

// ---------------------------------------------------------------------------
// 6. readiness polling
// ---------------------------------------------------------------------------

async function waitFor(name, check, timeoutMs = READY_TIMEOUT_MS) {
  const deadline = Date.now() + timeoutMs
  let lastError = 'check returned falsy'
  while (Date.now() < deadline) {
    try {
      if (await check()) {
        log('ready', `${name} is ready`)
        return true
      }
    }
    catch (error) {
      lastError = error instanceof Error ? error.message : String(error)
    }
    await new Promise(resolvePromise => setTimeout(resolvePromise, POLL_INTERVAL_MS))
  }
  console.error(`[smoke] ERROR: ${name} did not become ready within ${Math.round(timeoutMs / 1000)}s (last: ${lastError})`)
  return false
}

function httpsStatus(url, { auth } = {}) {
  const headers = {}
  if (auth) headers.authorization = `Basic ${Buffer.from(auth).toString('base64')}`
  return fetch(url, { headers, redirect: 'manual' }).then(res => res.status).catch((error) => {
    throw new Error(`GET ${url} failed: ${error instanceof Error ? error.message : String(error)}`)
  })
}

function dnsAnswer(name, server = '127.0.0.1', port = 53) {
  return new Promise((resolvePromise, rejectPromise) => {
    const id = Math.floor(Math.random() * 0xFFFF)
    const query = Buffer.alloc(12)
    query.writeUInt16BE(id, 0)
    query.writeUInt16BE(0x0100, 2) // RD=1
    query.writeUInt16BE(1, 4) // QDCOUNT
    const labels = name.split('.').map(part => `${String.fromCharCode(part.length)}${part}`).join('')
    const question = Buffer.from(`${labels}\u0000`, 'binary')
    const qtypeQclass = Buffer.from([0, 1, 0, 1]) // A, IN
    const packet = Buffer.concat([query, question, qtypeQclass])

    const socket = dgram.createSocket('udp4')
    const timer = setTimeout(() => {
      socket.close()
      rejectPromise(new Error(`DNS query to ${server}:${port} timed out`))
    }, 5000)
    socket.on('message', (msg) => {
      clearTimeout(timer)
      socket.close()
      const ancount = msg.readUInt16BE(6)
      if (ancount >= 1) resolvePromise(ancount)
      else rejectPromise(new Error(`DNS answered but no A record (ancount=${ancount})`))
    })
    socket.on('error', (error) => {
      clearTimeout(timer)
      socket.close()
      rejectPromise(error)
    })
    socket.send(packet, port, server)
  })
}

function tcpConnect(host, port) {
  return new Promise((resolvePromise, rejectPromise) => {
    const socket = net.connect({ host, port })
    const timer = setTimeout(() => {
      socket.destroy()
      rejectPromise(new Error(`TCP connect to ${host}:${port} timed out`))
    }, 5000)
    socket.on('connect', () => {
      clearTimeout(timer)
      socket.destroy()
      resolvePromise(true)
    })
    socket.on('error', (error) => {
      clearTimeout(timer)
      socket.destroy()
      rejectPromise(error)
    })
  })
}

function loadTestEnv() {
  return parseEnvFile(ENV_TEST)
}

async function waitForStack() {
  const env = loadTestEnv()
  const adminAuth = `${env.ADMIN_USERNAME}:${env.ADMIN_PASSWORD}`
  const checks = [
    ['bind9 DNS (A dev.gutschi.site @127.0.0.1:53)', () => dnsAnswer('dev.gutschi.site')],
    ['mock-oidc-server (https://127.0.0.1:8080/health)', () => httpsStatus('https://127.0.0.1:8080/health').then((s) => { if (s !== 200) throw new Error(`status ${s}`) })],
    ['SSH (TCP 127.0.0.1:2222)', () => tcpConnect('127.0.0.1', 2222)],
    ['application ping (https://www.gutschi.site/shared/ping)', () => httpsStatus('https://www.gutschi.site/shared/ping').then((s) => { if (s !== 200) throw new Error(`status ${s}`) })],
    ['dozzle UI (https://logs.gutschi.site)', () => httpsStatus('https://logs.gutschi.site', { auth: adminAuth }).then((s) => { if (s !== 200) throw new Error(`status ${s}`) })],
    ['pgweb UI (https://www.gutschi.site:8443)', () => httpsStatus('https://www.gutschi.site:8443', { auth: adminAuth }).then((s) => { if (s !== 200) throw new Error(`status ${s}`) })],
  ]

  let ok = true
  for (const [name, check] of checks) {
    ok = (await waitFor(name, check)) && ok
  }
  return ok
}

// ---------------------------------------------------------------------------
// 7. run the vitest checks
// ---------------------------------------------------------------------------

function runChecks() {
  log('checks', 'running vitest smoke checks')
  const result = spawnSync('pnpm', ['exec', 'vitest', 'run'], {
    cwd: PKG_ROOT,
    stdio: 'inherit',
    env: { ...process.env, NODE_TLS_REJECT_UNAUTHORIZED: '0' },
  })
  return result.status ?? 1
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

async function main() {
  requireDocker()
  generateCerts()
  ensureHosts()
  ensureProjectEnv()
  loadAiApiKey()

  let exitCode = 1
  try {
    composeUp()
    const ready = await waitForStack()
    if (!ready) {
      console.error('[smoke] ERROR: stack did not become ready; run with SMOKE_KEEP_STACK=1 to inspect')
    }
    else {
      exitCode = runChecks()
    }
  }
  catch (error) {
    console.error(`[smoke] ERROR: ${error instanceof Error ? error.message : String(error)}`)
  }
  finally {
    // Always tear down (also when compose up itself failed), unless the user
    // explicitly asked to keep the stack for debugging.
    composeDown()
  }

  if (exitCode === 0) log('done', 'smoke suite passed')
  else console.error(`[smoke] smoke suite failed (exit ${String(exitCode)})`)
  process.exit(exitCode)
}

void main()
