CREATE TABLE template (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL,
    language TEXT NOT NULL,
    text TEXT NOT NULL,
    owner_id TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);