description: Setup
inputs:
runs:
  using: "composite"
  steps:
  - name: Read nvmrc file
    run: echo ::set-output name=NVMRC::$(cat .nvmrc)
    id: nvm
  - name: Setup node
    uses: actions/setup-node@v1
    with:
      node-version: '${{ steps.nvm.outputs.NVMRC }}'
  - name: Setup pnpm
    uses: pnpm/action-setup@v4
  - name: Install dependencies
    run: pnpm i
