// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/cash": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/coeditor": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/cash" | "/admin" | "/coeditor";
  };
  "./cash/ProjectPage.tsx": {
    id: "cash/ProjectPage";
    page: "/cash";
  };
  "./admin/DashboardPage.tsx": {
    id: "admin/DashboardPage";
    page: "/admin";
  };
  "./coeditor/EditorPage.tsx": {
    id: "coeditor/EditorPage";
    page: "/coeditor";
  };
  "general/MainPage.tsx": {
    id: "general/MainPage";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "cash/ProjectPage": typeof import("./app/./cash/ProjectPage.tsx");
  "admin/DashboardPage": typeof import("./app/./admin/DashboardPage.tsx");
  "coeditor/EditorPage": typeof import("./app/./coeditor/EditorPage.tsx");
  "general/MainPage": typeof import("./app/general/MainPage.tsx");
};