import dgram from 'node:dgram'
import http from 'node:http'
import https from 'node:https'
import net from 'node:net'
import { createHash } from 'node:crypto'

// Plain HTTP/TLS helpers for the smoke checks. TLS verification is disabled
// deliberately: the stack runs on self-signed certificates (generated by
// integration-test/scripts/generate-certs.sh) and the suite is test-only.

export function httpsStatus(url: string, options: { auth?: string, timeoutMs?: number } = {}): Promise<number> {
  return new Promise((resolve, reject) => {
    const target = new URL(url)
    const request = https.request({
      hostname: target.hostname,
      port: target.port === '' ? undefined : Number(target.port),
      path: `${target.pathname}${target.search}`,
      method: 'GET',
      rejectUnauthorized: false,
      timeout: options.timeoutMs ?? 15_000,
      headers: {
        accept: '*/*',
        ...(options.auth ? { authorization: `Basic ${Buffer.from(options.auth).toString('base64')}` } : {}),
      },
    }, (response) => {
      response.resume()
      resolve(response.statusCode ?? 0)
    })
    request.on('timeout', () => request.destroy(new Error(`GET ${url} timed out`)))
    request.on('error', (error) => { reject(new Error(`GET ${url} failed: ${error.message}`, { cause: error })) })
    request.end()
  })
}

export function httpStatus(url: string, options: { timeoutMs?: number } = {}): Promise<number> {
  return new Promise((resolve, reject) => {
    const target = new URL(url)
    const request = http.request({
      hostname: target.hostname,
      port: target.port === '' ? undefined : Number(target.port),
      path: `${target.pathname}${target.search}`,
      method: 'GET',
      timeout: options.timeoutMs ?? 15_000,
    }, (response) => {
      response.resume()
      resolve(response.statusCode ?? 0)
    })
    request.on('timeout', () => request.destroy(new Error(`GET ${url} timed out`)))
    request.on('error', (error) => { reject(new Error(`GET ${url} failed: ${error.message}`, { cause: error })) })
    request.end()
  })
}

export function tcpConnect(host: string, port: number, timeoutMs = 10_000): Promise<void> {
  return new Promise((resolve, reject) => {
    const socket = net.connect({ host, port })
    const timer = setTimeout(() => {
      socket.destroy()
      reject(new Error(`TCP connect to ${host}:${String(port)} timed out`))
    }, timeoutMs)
    socket.on('connect', () => {
      clearTimeout(timer)
      socket.destroy()
      resolve()
    })
    socket.on('error', (error) => {
      clearTimeout(timer)
      socket.destroy()
      reject(new Error(`TCP connect to ${host}:${String(port)} failed: ${error.message}`))
    })
  })
}

// Minimal DNS client: sends an A query over UDP and resolves with the number of
// answer records, so the suite can assert that bind9 actually answers.
export function dnsAnswerCount(name: string, server = '127.0.0.1', port = 53): Promise<number> {
  return new Promise((resolve, reject) => {
    const id = Math.floor(Math.random() * 0xFFFF)
    const header = Buffer.alloc(12)
    header.writeUInt16BE(id, 0)
    header.writeUInt16BE(0x0100, 2) // RD=1
    header.writeUInt16BE(1, 4) // QDCOUNT=1
    const labels = name.split('.').map(part => `${String.fromCharCode(part.length)}${part}`).join('')
    const question = Buffer.from(`${labels}\u0000`, 'binary')
    const query = Buffer.concat([header, question, Buffer.from([0, 1, 0, 1])]) // A, IN

    const socket = dgram.createSocket('udp4')
    const timer = setTimeout(() => {
      socket.close()
      reject(new Error(`DNS query for ${name} @${server}:${String(port)} timed out`))
    }, 5_000)
    socket.on('message', (message) => {
      clearTimeout(timer)
      socket.close()
      resolve(message.readUInt16BE(6))
    })
    socket.on('error', (error) => {
      clearTimeout(timer)
      socket.close()
      reject(new Error(`DNS query for ${name} @${server}:${String(port)} failed: ${error.message}`))
    })
    socket.send(query, port, server)
  })
}

export function sha256Base64url(input: string): string {
  return createHash('sha256').update(input).digest('base64url')
}

export async function pollUntil<T>(check: () => Promise<T>, predicate: (value: T) => boolean, description: string, timeoutMs = 60_000, intervalMs = 2_000): Promise<T> {
  const deadline = Date.now() + timeoutMs
  let lastValue: T | undefined
  let lastError: unknown
  while (Date.now() < deadline) {
    try {
      lastValue = await check()
      if (predicate(lastValue)) return lastValue
    }
    catch (error) {
      lastError = error
    }
    await new Promise(resolve => setTimeout(resolve, intervalMs))
  }
  throw new Error(`${description} not satisfied within ${String(Math.round(timeoutMs / 1000))}s (last value: ${JSON.stringify(lastValue)}, last error: ${lastError instanceof Error ? lastError.message : String(lastError)})`)
}
