ALTER TABLE account_transaction DROP COLUMN project_id;
ALTER TABLE command ADD COLUMN owner_id TEXT NOT NULL DEFAULT 'unknown';
ALTER TABLE command ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;