name: "Frontend"
on: 
  push:
    paths:
    - '*'
    - 'backend/**'
    - '.github/**'
  pull_request:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint
        run: pnpm -F homeserver-backend run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run Tests
        run: pnpm -F homeserver-backend run test
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: pnpm -F homeserver-backend run build
      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: backend/build
          retention-days: 1
  deploy:
    name: Deploy
    needs: [build, test, lint]
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend
          path: backend/build
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform
        run:  |
          cd frontend
          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan
