name: "Build and Test"
on: push
jobs:
  webcomponents:
    name: Build and Test Webcomponents
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Read nvmrc file
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm i
      - name: Build Webcomponents
        run: pnpm -F homeserver-webcomponents run build
      - name: Lint Webcomponents
        run: pnpm -F homeserver-webcomponents run lint
      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install Playwright Browsers
        run: pnpm dlx  playwright install chromium --with-deps 
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - name: Run Webcomponents tests
        run: pnpm -F homeserver-webcomponents test
      - name: Run WebComponents Chromatic
        run: pnpm -F homeserver-webcomponents chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
