name: "Build and Test"
on: push
jobs:
  webcomponents:
    name: Run Web Components Tests
    runs-on: ubuntu-latest
    defaults:
      working-directory: ./webcomponents
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Read nvmrc file
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - name: Install dependencies
        run: pnpm ci
      - name: Lint
        run: pnpm lint
      - name: Run tests
        run: pnpm test
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}