name: "Frontend"
on: 
  push:
    paths:
    - '*'
    - 'webcomponents/**'
    - 'frontend/**'
    - '.github/**'
  pull_request:
jobs:
  buildwc:
    name: Build WebComponents
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Cache Webcomponents
        id: cache-webcomponents
        uses: actions/cache@v4
        with:
          path: webcomponents
          key: npm-${{ hashFiles('webcomponents/**') }}
      - name: Build
        if: steps.cache-webcomponents.outputs.cache-hit != 'true'
        run: pnpm -F homeserver-webcomponents run build
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: buildwc
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint
        run: pnpm -F homeserver-frontend run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: buildwc
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Cache Webcomponents
        uses: actions/cache@v4
        with:
          path: webcomponents
          key: npm-${{ hashFiles('webcomponents/**') }}
      - name: Run Tests
        run: pnpm -F homeserver-frontend run test
  build:
    name: Build
    needs: buildwc
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Cache Webcomponents
        uses: actions/cache@v4
        with:
          path: webcomponents
          key: npm-${{ hashFiles('webcomponents/**') }}
      - name: Build
        run: pnpm -F homeserver-frontend run build
  deploy:
    name: Deploy
    needs: [build, test, lint]
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Not implemented yet"
