name: "Frontend"
on: 
  push:
    paths:
    - '*'
    - 'webcomponents/**'
    - 'frontend/**'
    - '.github/**'
  pull_request:
jobs:
  buildwc:
    name: Build WebComponents
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: pnpm -F homeserver-webcomponents run build
      - name: Upload Webcomponents Build
        uses: actions/upload-artifact@v4
        with:
          name: webcomponents-build
          path: webcomponents/build
          retention-days: 1
      - name: Upload Webcomponents Dist
        uses: actions/upload-artifact@v4
        with:
          name: webcomponents-dist
          path: webcomponents/dist
          retention-days: 1
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint
        run: pnpm -F homeserver-frontend run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run Tests
        run: pnpm -F homeserver-frontend run test
  build:
    name: Build
    needs: buildwc
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Download Webcomponents Build
        uses: actions/download-artifact@v4
        with:
          name: webcomponents-build
          path: webcomponents/build
      - name: Download Webcomponents Dist
        uses: actions/download-artifact@v4
        with:
          name: webcomponents-dist
          path: webcomponents/dist
      - name: Build
        run: pnpm -F homeserver-frontend run build
      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: frontend/build/client
          retention-days: 1
  deploy:
    name: Deploy
    needs: [build, test, lint]
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend
          path: frontend/build/client
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform
        run:  |
          cd frontend
          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan
        env:
          access_key: ${{ secrets.SCW_ACCESS_KEY }}
          secret_key: ${{ secrets.SCW_SECRET_KEY  }}
          organization_id: ${{ vars.SCW_ORGANIZATION_ID }}
          project_id: ${{ vars.SCW_PROJECT_ID }}
          TFE_TOKEN: ${{ secrets.TF_TOKEN }}
