name: "Homeserver"
on: 
    push:
    workflow_dispatch:
jobs:
    lint:
        name: Lint Application
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Setup
            uses: ./.github/actions/setup
          - name: Lint
            run: pnpm run lint
    test:
        name: Test Application (Unit)
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Setup
            uses: ./.github/actions/setup
          - name: Cache Playwright Browsers
            uses: actions/cache@v3
            id: playwright-cache
            with:
                path: ~/.cache/ms-playwright
                key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          - name: Install Playwright Browsers
            run: pnpm exec playwright install --with-deps
            if: ${{ steps.playwright-cache.outputs.cache-hit != 'true' }}
          - name: Tests
            run: pnpm run test
    chromatic:
        name: Test Application (Chromatic)
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
               fetch-depth: 0
          - name: Setup
            uses: ./.github/actions/setup
          - name: Cache Playwright Browsers
            uses: actions/cache@v3
            id: playwright-cache
            with:
                path: ~/.cache/ms-playwright
                key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          - name: Install Playwright Browsers
            run: pnpm exec playwright install --with-deps
            if: ${{ steps.playwright-cache.outputs.cache-hit != 'true' }}
          - name: Chromatic
            run: pnpm run chromatic
            env:
                CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
    build:
        name: Build Docker Container
        runs-on: ubuntu-latest        
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: Build Docker
            uses: docker/build-push-action@v6
            with:
              context: .
              platforms: linux/amd64
              push: false
              tags: myimage:latest
              cache-from: type=gha
              cache-to: type=gha,mode=max 
              outputs: type=docker,dest=${{ runner.temp }}/myimage.tar
              build-args: |
                GIT_COMMIT_HASH=${{ github.sha }}
                GIT_BRANCH=${{ github.ref_name }}
                GITHUB_RUN_ID=${{ github.run_id }}
                BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          - name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
              name: myimage
              path: ${{ runner.temp }}/myimage.tar
    infrastructure:
        name: Check Infrastructure
        runs-on: ubuntu-latest
        env:
            TF_CLOUD_ORGANIZATION: "gutschi-site"
            TF_API_TOKEN: "${{ secrets.TF_TOKEN }}"
            TF_WORKSPACE: "homesever-cicd"
            CONFIG_DIRECTORY: "./"
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Upload Configuration
            uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
            id: apply-upload
            with:
                directory: "./infrastructure"
                workspace: ${{ env.TF_WORKSPACE }}
          - name: Create Plan Run
            uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
            id: plan-run
            with:
                plan_only: true
                workspace: ${{ env.TF_WORKSPACE }}
                configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}
          - name: Get Plan Output
            uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.0.0
            id: plan-output
            with:
              plan: ${{ fromJSON(steps.plan-run.outputs.payload).data.relationships.plan.data.id }}
          - name: Check for changes
            run: |
              if ((${{ steps.plan-output.outputs.add }} + ${{ steps.plan-output.outputs.change }} + ${{ steps.plan-output.outputs.destroy }} == 0 )); then
                echo "No changes detected in infrastructure."
                exit 0
              else
                echo "Changes detected in infrastructure! ${{ steps.plan-output.outputs.add }} to add, ${{ steps.plan-output.outputs.change }} to change, ${{ steps.plan-output.outputs.destroy }} to destroy."
                echo "See ${{ steps.plan-run.outputs.run_link }} for details."
                echo "Updating infrastructure manually."
                exit -1
              fi
    deploy:
        name: Push Docker Container and restart
        needs: [lint, test, chromatic, build, infrastructure]
        runs-on: ubuntu-latest        
        env:
            registry: rg.fr-par.scw.cloud/funcscwgutschisitewsdlddur
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Set Environment Variables (Prod)
            if : github.ref == 'refs/heads/main'
            run: |
              echo "container_tag=latest" >> $GITHUB_ENV
              echo "container_id=606c9f62-bceb-484c-a576-679874d37517" >> $GITHUB_ENV
          - name: Set Environment Variables (Test)
            if : github.ref != 'refs/heads/main'
            run: |
              echo "container_tag=test" >> $GITHUB_ENV
              echo "container_id=89160430-514c-49ef-a53d-9e936beaec8a" >> $GITHUB_ENV
          - name: Login to Registry
            uses: docker/login-action@v3
            with:
              username: nologin
              password: ${{ secrets.SCW_SECRET_KEY }}
              registry: ${{env.registry}}
          - name: Download artifact
            uses: actions/download-artifact@v4
            with:
              name: myimage
              path: ${{ runner.temp }}
          - name: Load image
            run: docker load --input ${{ runner.temp }}/myimage.tar
          - name: Tag image
            run: docker tag myimage:latest ${{env.registry}}/www_gutschi_site:${{env.container_tag}}
          - name: Docker Push
            run: docker push  ${{env.registry}}/www_gutschi_site:${{env.container_tag}}
          - name: Restart Container
            run: |
              # deploy the container using the API
              curl --silent --fail -o /dev/null -w "Response: %{http_code}\n" \
                --request POST \
                --header "X-Auth-Token: ${{ secrets.SCW_SECRET_KEY }}" \
                --data '{}' \
                https://api.scaleway.com/containers/v1beta1/regions/fr-par/containers/${{env.container_id}}/deploy
