name: "Test Frontend"
run-name: "Test Frontend (${{ github.event.head_commit.message.id || github.event.pull_request.title || github.sha }})"
on: 
  push:
    paths:
    - 'frontend/**'
    - '.github/**'
  pull_request:
jobs:
  test:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: pnpm -F homeserver-frontend run build
      - name: Lint
        run: pnpm -F homeserver-frontend run lint
      - name: Run Tests
        run: pnpm -F homeserver-frontend run test
