name: "Webcomponents"
run-name: "Webcomponents (${{(github.event.head_commit && github.event.head_commit.message) || (github.event.pull_request && format('Pull Request {0}', github.event.pull_request.title)) || github.sha }})"
on: 
  push:
    paths:
    - '*'
    - 'webcomponents/**'
    - '.github/**'
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint
        run: pnpm -F homeserver-webcomponents run lint
      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install Playwright Browsers
        run: pnpm dlx  playwright install chromium --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - name: Tests
        run: pnpm -F homeserver-webcomponents run test
      - name: Chromatic
        run: pnpm -F homeserver-webcomponents run chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
  build:
    name: Build
    needs: test
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: pnpm -F homeserver-webcomponents run build
